import { formatColor, toHex, toRgb } from "@/lib/color/color";
import { colorTokens } from "@/lib/color/export";
import { gradientCss, gradientCssFallback } from "@/lib/color/gradient";
import { fontStack } from "@/lib/typography/css";
import { siteConfig } from "@/lib/site";
import { googleFontsCssUrl } from "@/lib/typography/google-fonts";
import type { ExportFormat } from "@/types/export";
import type { Oklch } from "@/types/color";
import type { DesignTokens } from "@/types/tokens";

export type FlatToken = { group: string; name: string; value: string };
type Flat = FlatToken[];

const px = (value: number) => (value >= 9999 ? "9999px" : value === 0 ? "0" : `${value / 16}rem`);

/** One flat list drives every text format, so they can never disagree. */
export function flatten(tokens: DesignTokens): Flat {
  const color = (value: Oklch) => formatColor(value, tokens.meta.colorFormat);
  const list: Flat = [];

  tokens.colors.forEach((token) => {
    list.push({ group: "color", name: `color-${token.name}`, value: color(token.value) });
    token.shades.forEach((shade) =>
      list.push({ group: "color", name: `color-${token.name}-${shade.step}`, value: color(shade.value) }),
    );
  });
  tokens.semantic.forEach((role) =>
    list.push({ group: "semantic", name: `color-${role.name}`, value: color(role.value) }),
  );
  if (tokens.gradient) list.push({ group: "gradient", name: "gradient-primary", value: gradientCss(tokens.gradient) });

  const t = tokens.typography;
  if (t) {
    list.push({ group: "font", name: "font-heading", value: fontStack(t.heading.family, t.heading.category) });
    list.push({ group: "font", name: "font-body", value: fontStack(t.body.family, t.body.category) });
    list.push({ group: "font", name: "font-weight-heading", value: String(t.rhythm.headingWeight) });
    list.push({ group: "font", name: "font-weight-body", value: String(t.rhythm.bodyWeight) });
    list.push({ group: "font", name: "leading-heading", value: String(t.rhythm.headingLineHeight) });
    list.push({ group: "font", name: "leading-body", value: String(t.rhythm.bodyLineHeight) });
    list.push({ group: "font", name: "tracking-heading", value: `${t.rhythm.headingTracking}em` });
    list.push({ group: "font", name: "tracking-body", value: `${t.rhythm.bodyTracking}em` });
    t.steps.forEach((step) => list.push({ group: "text", name: `text-${step.name}`, value: step.clamp }));
  }
  tokens.spacing.forEach((step) => list.push({ group: "spacing", name: `spacing-${step.name}`, value: px(step.px) }));
  tokens.radius.forEach((step) => list.push({ group: "radius", name: `radius-${step.name}`, value: px(step.px) }));
  tokens.effects.forEach((effect) => list.push({ group: "effect", name: effect.name, value: effect.value }));
  return list;
}

const header = (tokens: DesignTokens, comment: (text: string) => string) =>
  comment(`${tokens.meta.name} - design tokens generated by DesignHub (${siteConfig.github})`);

/** CSS custom property names can't contain a bare "." (spacing-0.5), so escape it. */
const cssIdent = (name: string) => name.replace(/\./g, "\\.");

export function variable(tokens: DesignTokens, name: string): string {
  return `--${tokens.meta.prefix ? `${tokens.meta.prefix}-` : ""}${cssIdent(name)}`;
}

function fontImport(tokens: DesignTokens): string {
  const t = tokens.typography;
  if (!t) return "";
  const fonts = t.heading.family === t.body.family ? [t.heading] : [t.heading, t.body];
  return `@import url("${googleFontsCssUrl(fonts)}");\n\n`;
}

export function toCss(tokens: DesignTokens): string {
  const flat = flatten(tokens);
  const lines = flat.map((token) => {
    // Semantic colors reference the palette so rebranding is a one-line change.
    const role = tokens.semantic.find((item) => `color-${item.name}` === token.name);
    const inPalette = role && tokens.colors.some((color) => color.name === role.ref);
    const value = role && inPalette ? `var(${variable(tokens, `color-${role.ref}`)}, ${token.value})` : token.value;
    return `  ${variable(tokens, token.name)}: ${value};`;
  });
  const fallback = tokens.gradient
    ? `\n@supports not (background: linear-gradient(in oklch, red, blue)) {\n  :root {\n    ${variable(tokens, "gradient-primary")}: ${gradientCssFallback(tokens.gradient)};\n  }\n}\n`
    : "";
  return `${header(tokens, (text) => `/* ${text} */`)}\n${fontImport(tokens)}:root {\n${lines.join("\n")}\n}\n${fallback}`;
}

export function toScss(tokens: DesignTokens): string {
  const flat = flatten(tokens);
  const name = (token: string) => `$${tokens.meta.prefix ? `${tokens.meta.prefix}-` : ""}${token.replace(/\./g, "_")}`;
  const vars = flat.map((token) => `${name(token.name)}: ${token.value};`).join("\n");
  const map = (group: string, strip: string) =>
    flat
      .filter((token) => token.group === group)
      .map((token) => `  "${token.name.replace(strip, "")}": ${name(token.name)},`)
      .join("\n");
  const maps = [
    tokens.colors.length ? `$colors: (\n${map("color", "color-")}\n);` : "",
    tokens.typography ? `$type-scale: (\n${map("text", "text-")}\n);` : "",
    tokens.spacing.length ? `$spacing: (\n${map("spacing", "spacing-")}\n);` : "",
    tokens.radius.length ? `$radii: (\n${map("radius", "radius-")}\n);` : "",
  ]
    .filter(Boolean)
    .join("\n\n");
  return `${header(tokens, (text) => `// ${text}`)}\n@use "sass:map";\n\n${vars}\n\n${maps}\n`;
}

/**
 * Less variables. Values with functions (clamp, gradients, shadows with rgb()) are escaped
 * with ~"..." so Less passes them through instead of trying to evaluate the math.
 */
export function toLess(tokens: DesignTokens): string {
  const name = (token: string) => `@${tokens.meta.prefix ? `${tokens.meta.prefix}-` : ""}${token.replace(/\./g, "_")}`;
  const value = (raw: string) => (raw.includes("(") ? `~"${raw.replace(/"/g, '\\"')}"` : raw);
  const vars = flatten(tokens)
    .map((token) => `${name(token.name)}: ${value(token.value)};`)
    .join("\n");
  return `${header(tokens, (text) => `// ${text}`)}\n${vars}\n`;
}

/** Android `res/values/colors.xml`: palette, shades and semantic roles as #AARRGGBB resources. */
export function toAndroidColors(tokens: DesignTokens): string {
  const prefix = tokens.meta.prefix ? `${tokens.meta.prefix}_` : "";
  // Resource names allow only lowercase letters, digits and underscores, and can't start with a digit.
  const resource = (name: string) => {
    const clean = `${prefix}${name}`
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "");
    return /^[0-9]/.test(clean) ? `c_${clean}` : clean;
  };
  const argb = (value: Oklch) => {
    const { r, g, b, alpha } = toRgb(value);
    return `#${[Math.round(alpha * 255), r, g, b]
      .map((channel) => channel.toString(16).padStart(2, "0"))
      .join("")
      .toUpperCase()}`;
  };
  const seen = new Set<string>();
  const lines: string[] = [];
  const add = (name: string, value: Oklch) => {
    const id = resource(name);
    if (!id || seen.has(id)) return;
    seen.add(id);
    lines.push(`    <color name="${id}">${argb(value)}</color>`);
  };
  tokens.colors.forEach((token) => {
    add(token.name, token.value);
    token.shades.forEach((shade) => add(`${token.name}_${shade.step}`, shade.value));
  });
  tokens.semantic.forEach((role) => add(role.name, role.value));
  // "--" is not allowed inside XML comments.
  const comment = header(tokens, (text) => `<!-- ${text.replace(/-{2,}/g, "-")} -->`);
  return `<?xml version="1.0" encoding="utf-8"?>\n${comment}\n<resources>\n${lines.join("\n")}\n</resources>\n`;
}

/** Tailwind v4 reads design tokens from CSS `@theme` variables. */
export function toTailwindV4(tokens: DesignTokens): string {
  // DesignHub token names already follow Tailwind v4's theme namespaces (--color-*, --text-*, --radius-*…).
  const lines = flatten(tokens).map((token) => `  --${cssIdent(token.name)}: ${token.value};`);
  return `${header(tokens, (text) => `/* ${text} */`)}\n@import "tailwindcss";\n${fontImport(tokens)}\n@theme {\n${lines.join("\n")}\n}\n`;
}

export function toTailwindConfig(tokens: DesignTokens): string {
  const color = (value: Oklch) => formatColor(value, tokens.meta.colorFormat);
  const colors = Object.fromEntries([
    ...tokens.colors.map((token) => [
      token.name,
      token.shades.length
        ? { DEFAULT: color(token.value), ...Object.fromEntries(token.shades.map((s) => [s.step, color(s.value)])) }
        : color(token.value),
    ]),
    ...tokens.semantic.map((role) => [role.name, color(role.value)]),
  ]);
  const t = tokens.typography;
  const theme = {
    colors,
    ...(t
      ? {
          fontFamily: {
            heading: [t.heading.family, t.heading.category],
            body: [t.body.family, t.body.category],
          },
          fontSize: Object.fromEntries(
            t.steps.map((step) => [
              step.name,
              [
                step.clamp,
                { lineHeight: String(step.step > 0 ? t.rhythm.headingLineHeight : t.rhythm.bodyLineHeight) },
              ],
            ]),
          ),
        }
      : {}),
    ...(tokens.spacing.length ? { spacing: Object.fromEntries(tokens.spacing.map((s) => [s.name, px(s.px)])) } : {}),
    ...(tokens.radius.length ? { borderRadius: Object.fromEntries(tokens.radius.map((r) => [r.name, px(r.px)])) } : {}),
    ...(tokens.gradient ? { backgroundImage: { "gradient-primary": gradientCss(tokens.gradient) } } : {}),
  };
  return `${header(tokens, (text) => `// ${text}`)}
// Tailwind CSS v3 - for v4 use the CSS @theme export instead.
import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{ts,tsx,js,jsx,html}"],
  theme: {
    extend: ${JSON.stringify(theme, null, 2).replace(/\n/g, "\n    ")},
  },
} satisfies Config;
`;
}

export function toReactTheme(tokens: DesignTokens): string {
  const groups = new Map<string, Record<string, string>>();
  flatten(tokens).forEach((token) => {
    const key = token.group === "semantic" ? "color" : token.group;
    const name = token.name.replace(/^(color|gradient|font|text|spacing|radius)-/, "");
    groups.set(key, { ...(groups.get(key) ?? {}), [name]: token.value });
  });
  const theme = Object.fromEntries(groups);
  return `${header(tokens, (text) => `// ${text}`)}
import type { CSSProperties } from "react";

export const theme = ${JSON.stringify(theme, null, 2)} as const;

export type Theme = typeof theme;

/** Spread onto a root element to expose the theme as CSS variables: <div style={themeVars}>. */
export const themeVars = Object.fromEntries(
  Object.entries(theme).flatMap(([group, values]) =>
    Object.entries(values).map(([name, value]) => [\`--\${group}-\${name}\`, value]),
  ),
) as CSSProperties;
`;
}

/** Vue 3: the theme object, an injection key and a plugin that exposes it as CSS variables. */
export function toVueTheme(tokens: DesignTokens): string {
  const groups = new Map<string, Record<string, string>>();
  flatten(tokens).forEach((token) => {
    const key = token.group === "semantic" ? "color" : token.group;
    const name = token.name.replace(/^(color|gradient|font|text|spacing|radius)-/, "");
    groups.set(key, { ...(groups.get(key) ?? {}), [name]: token.value });
  });
  const theme = Object.fromEntries(groups);
  return `${header(tokens, (text) => `// ${text}`)}
import { inject, type App, type InjectionKey } from "vue";

export const theme = ${JSON.stringify(theme, null, 2)} as const;

export type Theme = typeof theme;

export const themeKey: InjectionKey<Theme> = Symbol("theme");

/** CSS variables for the theme, e.g. --color-primary. */
export const themeVars: Record<string, string> = Object.fromEntries(
  Object.entries(theme).flatMap(([group, values]) =>
    Object.entries(values).map(([name, value]) => [\`--\${group}-\${name}\`, value]),
  ),
);

/** app.use(themePlugin) provides the theme and writes its variables onto :root. */
export const themePlugin = {
  install(app: App) {
    app.provide(themeKey, theme);
    if (typeof document !== "undefined") {
      Object.entries(themeVars).forEach(([name, value]) => document.documentElement.style.setProperty(name, value));
    }
  },
};

/** Read the theme inside a component: const theme = useTheme(). */
export function useTheme(): Theme {
  return inject(themeKey, theme);
}
`;
}

export function toJsonTokens(tokens: DesignTokens): string {
  const palette = tokens.colors.map((token) => ({
    name: token.name,
    color: token.value,
    shades: token.shades.map((shade) => ({ step: shade.step, color: shade.value })),
  }));
  const colors = colorTokens(
    palette,
    tokens.colors.some((token) => token.shades.length > 0),
    tokens.gradient ?? undefined,
  );
  const dimension = (value: number) => ({
    value: value >= 9999 ? 9999 : value / 16,
    unit: value >= 9999 ? "px" : "rem",
  });
  const t = tokens.typography;

  const document = {
    $description: `${tokens.meta.name} - generated by DesignHub on ${tokens.meta.generatedAt}`,
    ...colors,
    ...(tokens.semantic.length
      ? {
          semantic: Object.fromEntries(
            tokens.semantic.map((role) => {
              const source = tokens.colors.find((color) => color.name === role.ref);
              // Aliases only resolve to palette colors; synthesized white/black are written as values.
              const $value = source
                ? `{color.${role.ref}${source.shades.length ? ".DEFAULT" : ""}}`
                : {
                    colorSpace: "oklch",
                    components: [role.value.l, role.value.c, role.value.h],
                    hex: toHex(role.value),
                  };
              return [role.name, { $type: "color", $value }];
            }),
          ),
        }
      : {}),
    ...(t
      ? {
          font: {
            family: {
              heading: { $type: "fontFamily", $value: [t.heading.family, t.heading.category] },
              body: { $type: "fontFamily", $value: [t.body.family, t.body.category] },
            },
            weight: {
              heading: { $type: "fontWeight", $value: t.rhythm.headingWeight },
              body: { $type: "fontWeight", $value: t.rhythm.bodyWeight },
            },
            size: Object.fromEntries(
              t.steps.map((step) => [
                step.name,
                {
                  $type: "dimension",
                  $value: dimension(step.maxPx),
                  $extensions: { "dev.designhub.fluid": { min: dimension(step.minPx), css: step.clamp } },
                },
              ]),
            ),
          },
        }
      : {}),
    ...(tokens.spacing.length
      ? {
          spacing: Object.fromEntries(
            tokens.spacing.map((s) => [s.name, { $type: "dimension", $value: dimension(s.px) }]),
          ),
        }
      : {}),
    ...(tokens.radius.length
      ? {
          radius: Object.fromEntries(
            tokens.radius.map((r) => [r.name, { $type: "dimension", $value: dimension(r.px) }]),
          ),
        }
      : {}),
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

export function tokenFormats(tokens: DesignTokens): ExportFormat[] {
  return [
    { id: "css", label: "CSS variables", filename: "tokens.css", language: "css", code: toCss(tokens) },
    { id: "scss", label: "SCSS", filename: "_tokens.scss", language: "scss", code: toScss(tokens) },
    { id: "less", label: "Less", filename: "tokens.less", language: "css", code: toLess(tokens) },
    { id: "android", label: "Android XML", filename: "colors.xml", language: "xml", code: toAndroidColors(tokens) },
    { id: "tailwind-v4", label: "Tailwind v4", filename: "theme.css", language: "css", code: toTailwindV4(tokens) },
    {
      id: "tailwind-config",
      label: "Tailwind config",
      filename: "tailwind.config.ts",
      language: "ts",
      code: toTailwindConfig(tokens),
    },
    { id: "react", label: "React theme", filename: "theme.ts", language: "ts", code: toReactTheme(tokens) },
    { id: "vue", label: "Vue theme", filename: "theme.ts", language: "ts", code: toVueTheme(tokens) },
    { id: "json", label: "JSON tokens", filename: "tokens.json", language: "json", code: toJsonTokens(tokens) },
  ];
}

export function paletteHexes(tokens: DesignTokens): { name: string; hex: string }[] {
  return tokens.colors.map((token) => ({ name: token.name, hex: toHex(token.value) }));
}
