import { formatColor, toHex, toRgb } from "@/lib/color/color";
import { colorTokens } from "@/lib/color/export";
import { gradientCss, gradientCssFallback } from "@/lib/color/gradient";
import { fontStack } from "@/lib/typography/css";
import { siteConfig } from "@/lib/site";
import {
  roleColor,
  toComposeTheme,
  toFlutterTheme,
  toSwiftUITheme,
  toTokensStudio,
  type RoleColor,
} from "@/lib/tokens/native";
import { googleFontsCssUrl } from "@/lib/typography/google-fonts";
import type { ExportFormat } from "@/types/export";
import type { Oklch } from "@/types/color";
import type { DesignTokens } from "@/types/tokens";

export type FlatToken = { group: string; name: string; value: string };
type Flat = FlatToken[];

const px = (value: number) => (value >= 9999 ? "9999px" : value === 0 ? "0" : `${value / 16}rem`);

/** One flat list drives every text format, so they can never disagree. */
export function flatten(tokens: DesignTokens): Flat {
  const color = (value: Oklch) => formatColor(value, tokens.meta.colorFormat);
  const list: Flat = [];

  tokens.colors.forEach((token) => {
    list.push({ group: "color", name: `color-${token.name}`, value: color(token.value) });
    token.shades.forEach((shade) =>
      list.push({ group: "color", name: `color-${token.name}-${shade.step}`, value: color(shade.value) }),
    );
  });
  tokens.semantic.forEach((role) =>
    list.push({ group: "semantic", name: `color-${role.name}`, value: color(role.value) }),
  );
  if (tokens.gradient) list.push({ group: "gradient", name: "gradient-primary", value: gradientCss(tokens.gradient) });

  const t = tokens.typography;
  if (t) {
    list.push({ group: "font", name: "font-heading", value: fontStack(t.heading.family, t.heading.category) });
    list.push({ group: "font", name: "font-body", value: fontStack(t.body.family, t.body.category) });
    list.push({ group: "font", name: "font-weight-heading", value: String(t.rhythm.headingWeight) });
    list.push({ group: "font", name: "font-weight-body", value: String(t.rhythm.bodyWeight) });
    list.push({ group: "font", name: "leading-heading", value: String(t.rhythm.headingLineHeight) });
    list.push({ group: "font", name: "leading-body", value: String(t.rhythm.bodyLineHeight) });
    list.push({ group: "font", name: "tracking-heading", value: `${t.rhythm.headingTracking}em` });
    list.push({ group: "font", name: "tracking-body", value: `${t.rhythm.bodyTracking}em` });
    t.steps.forEach((step) => list.push({ group: "text", name: `text-${step.name}`, value: step.clamp }));
  }
  tokens.spacing.forEach((step) => list.push({ group: "spacing", name: `spacing-${step.name}`, value: px(step.px) }));
  tokens.radius.forEach((step) => list.push({ group: "radius", name: `radius-${step.name}`, value: px(step.px) }));
  tokens.effects.forEach((effect) => list.push({ group: "effect", name: effect.name, value: effect.value }));
  return list;
}

const header = (tokens: DesignTokens, comment: (text: string) => string) =>
  comment(`${tokens.meta.name} - design tokens generated by DesignHub (${siteConfig.github})`);

/** CSS custom property names can't contain a bare "." (spacing-0.5), so escape it. */
const cssIdent = (name: string) => name.replace(/\./g, "\\.");

export function variable(tokens: DesignTokens, name: string): string {
  return `--${tokens.meta.prefix ? `${tokens.meta.prefix}-` : ""}${cssIdent(name)}`;
}

function fontImport(tokens: DesignTokens): string {
  const t = tokens.typography;
  if (!t) return "";
  const fonts = t.heading.family === t.body.family ? [t.heading] : [t.heading, t.body];
  return `@import url("${googleFontsCssUrl(fonts)}");\n\n`;
}

export function toCss(tokens: DesignTokens): string {
  const flat = flatten(tokens);
  const lines = flat.map((token) => {
    // Semantic colors reference the palette so rebranding is a one-line change.
    const role = tokens.semantic.find((item) => `color-${item.name}` === token.name);
    const inPalette = role && tokens.colors.some((color) => color.name === role.ref);
    const value = role && inPalette ? `var(${variable(tokens, `color-${role.ref}`)}, ${token.value})` : token.value;
    return `  ${variable(tokens, token.name)}: ${value};`;
  });
  const fallback = tokens.gradient
    ? `\n@supports not (background: linear-gradient(in oklch, red, blue)) {\n  :root {\n    ${variable(tokens, "gradient-primary")}: ${gradientCssFallback(tokens.gradient)};\n  }\n}\n`
    : "";
  return `${header(tokens, (text) => `/* ${text} */`)}\n${fontImport(tokens)}:root {\n${lines.join("\n")}\n}\n${fallback}`;
}

export function toScss(tokens: DesignTokens): string {
  const flat = flatten(tokens);
  const name = (token: string) => `$${tokens.meta.prefix ? `${tokens.meta.prefix}-` : ""}${token.replace(/\./g, "_")}`;
  const vars = flat.map((token) => `${name(token.name)}: ${token.value};`).join("\n");
  const map = (group: string, strip: string) =>
    flat
      .filter((token) => token.group === group)
      .map((token) => `  "${token.name.replace(strip, "")}": ${name(token.name)},`)
      .join("\n");
  const maps = [
    tokens.colors.length ? `$colors: (\n${map("color", "color-")}\n);` : "",
    tokens.typography ? `$type-scale: (\n${map("text", "text-")}\n);` : "",
    tokens.spacing.length ? `$spacing: (\n${map("spacing", "spacing-")}\n);` : "",
    tokens.radius.length ? `$radii: (\n${map("radius", "radius-")}\n);` : "",
  ]
    .filter(Boolean)
    .join("\n\n");
  return `${header(tokens, (text) => `// ${text}`)}\n@use "sass:map";\n\n${vars}\n\n${maps}\n`;
}

/**
 * Less variables. Values with functions (clamp, gradients, shadows with rgb()) are escaped
 * with ~"..." so Less passes them through instead of trying to evaluate the math.
 */
export function toLess(tokens: DesignTokens): string {
  const name = (token: string) => `@${tokens.meta.prefix ? `${tokens.meta.prefix}-` : ""}${token.replace(/\./g, "_")}`;
  const value = (raw: string) => (raw.includes("(") ? `~"${raw.replace(/"/g, '\\"')}"` : raw);
  const vars = flatten(tokens)
    .map((token) => `${name(token.name)}: ${value(token.value)};`)
    .join("\n");
  return `${header(tokens, (text) => `// ${text}`)}\n${vars}\n`;
}

/**
 * Stylus variables with the same names as the SCSS export, plus hashes for each scale.
 * Values with functions (clamp, gradients, rgb() with a "/") go through unquote() so Stylus
 * passes them through instead of evaluating the math.
 */
export function toStylus(tokens: DesignTokens): string {
  const flat = flatten(tokens);
  const name = (token: string) => `$${tokens.meta.prefix ? `${tokens.meta.prefix}-` : ""}${token.replace(/\./g, "_")}`;
  const value = (raw: string) => (raw.includes("(") ? `unquote(${JSON.stringify(raw)})` : raw);
  const vars = flat.map((token) => `${name(token.name)} = ${value(token.value)}`).join("\n");
  const hash = (group: string, strip: string) =>
    flat
      .filter((token) => token.group === group)
      .map((token) => `  "${token.name.replace(strip, "")}": ${name(token.name)}`)
      .join("\n");
  const hashes = [
    tokens.colors.length ? `$colors = {\n${hash("color", "color-")}\n}` : "",
    tokens.typography ? `$type-scale = {\n${hash("text", "text-")}\n}` : "",
    tokens.spacing.length ? `$spacing = {\n${hash("spacing", "spacing-")}\n}` : "",
    tokens.radius.length ? `$radii = {\n${hash("radius", "radius-")}\n}` : "",
  ]
    .filter(Boolean)
    .join("\n\n");
  return `${header(tokens, (text) => `// ${text}`)}\n${vars}\n${hashes ? `\n${hashes}\n` : ""}`;
}

/** Groups and keys shared by the YAML and Sass map exports: the flat names without their group prefix. */
function groupedTokens(tokens: DesignTokens, prefix = ""): Map<string, Map<string, string>> {
  const groups = new Map<string, Map<string, string>>();
  flatten(tokens).forEach((token) => {
    const key = `${prefix}${token.name.replace(/^(color|gradient|font|text|spacing|radius)-/, "")}`;
    groups.set(token.group, (groups.get(token.group) ?? new Map()).set(key, token.value));
  });
  return groups;
}

// YAML 1.1 and 1.2 read these plain scalars as booleans, null or numbers instead of strings.
const yamlReserved = /^(y|n|yes|no|on|off|true|false|null|~|[-+]?\.?(inf|nan))$/i;
const yamlNumber =
  /^[-+]?(0x[0-9a-f_]+|0o?[0-7_]+|0b[01_]+|[0-9][0-9_]*(\.[0-9_]*)?(e[-+]?[0-9]+)?|\.[0-9_]+(e[-+]?[0-9]+)?)$/i;

/**
 * A YAML scalar that always reads back as the same string. Plain words like `0.125rem` stay
 * bare; anything YAML could misread (`#fff` is a comment, `0.5` a number, `yes` a boolean,
 * `: ` a mapping) is double quoted, and a JSON string is a valid double-quoted YAML scalar.
 */
export function yamlString(value: string): string {
  const plain = /^[A-Za-z0-9][\w.%-]*$/.test(value) && !yamlReserved.test(value) && !yamlNumber.test(value);
  return plain ? value : JSON.stringify(value);
}

/** YAML (tokens.yaml): one mapping per group, written by hand so it needs no dependency. */
export function toYaml(tokens: DesignTokens): string {
  const groups = groupedTokens(tokens, tokens.meta.prefix ? `${tokens.meta.prefix}-` : "");
  const body = [...groups]
    .map(([group, values]) => {
      const rows = [...values].map(([key, value]) => `  ${yamlString(key)}: ${yamlString(value)}`);
      return `${group}:\n${rows.join("\n")}`;
    })
    .join("\n");
  return `${header(tokens, (text) => `# ${text}`)}\n${body}\n`;
}

/**
 * Sass map (_tokens-map.scss): every group as a nested map plus a `token($group, $name)`
 * lookup. Keys are quoted strings and the function interpolates its arguments, so
 * `token(spacing, 4)` and `token("spacing", "4")` find the same entry.
 */
export function toSassMap(tokens: DesignTokens): string {
  // Commas separate map entries, so values with a comma (font stacks, layered shadows) get parentheses.
  const value = (raw: string) => (raw.includes(",") ? `(${raw})` : raw);
  const groups = [...groupedTokens(tokens)]
    .map(([group, values]) => {
      const rows = [...values].map(([key, raw]) => `    "${key}": ${value(raw)},`);
      return `  "${group}": (\n${rows.join("\n")}\n  ),`;
    })
    .join("\n");
  return `${header(tokens, (text) => `// ${text}`)}
@use "sass:map";

$tokens: (
${groups}
);

/// Looks up one token, e.g. color: token(semantic, primary); or padding: token(spacing, 4);
@function token($group, $name) {
  $group: "#{$group}";
  $name: "#{$name}";
  @if not map.has-key($tokens, $group, $name) {
    @error "Unknown token #{$group}.#{$name}";
  }
  @return map.get($tokens, $group, $name);
}
`;
}

/** Android `res/values/colors.xml`: palette, shades and semantic roles as #AARRGGBB resources. */
export function toAndroidColors(tokens: DesignTokens): string {
  const prefix = tokens.meta.prefix ? `${tokens.meta.prefix}_` : "";
  // Resource names allow only lowercase letters, digits and underscores, and can't start with a digit.
  const resource = (name: string) => {
    const clean = `${prefix}${name}`
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "");
    return /^[0-9]/.test(clean) ? `c_${clean}` : clean;
  };
  const argb = (value: Oklch) => {
    const { r, g, b, alpha } = toRgb(value);
    return `#${[Math.round(alpha * 255), r, g, b]
      .map((channel) => channel.toString(16).padStart(2, "0"))
      .join("")
      .toUpperCase()}`;
  };
  const seen = new Set<string>();
  const lines: string[] = [];
  const add = (name: string, value: Oklch) => {
    const id = resource(name);
    if (!id || seen.has(id)) return;
    seen.add(id);
    lines.push(`    <color name="${id}">${argb(value)}</color>`);
  };
  tokens.colors.forEach((token) => {
    add(token.name, token.value);
    token.shades.forEach((shade) => add(`${token.name}_${shade.step}`, shade.value));
  });
  tokens.semantic.forEach((role) => add(role.name, role.value));
  // "--" is not allowed inside XML comments.
  const comment = header(tokens, (text) => `<!-- ${text.replace(/-{2,}/g, "-")} -->`);
  return `<?xml version="1.0" encoding="utf-8"?>\n${comment}\n<resources>\n${lines.join("\n")}\n</resources>\n`;
}

/** Tailwind v4 reads design tokens from CSS `@theme` variables. */
export function toTailwindV4(tokens: DesignTokens): string {
  // DesignHub token names already follow Tailwind v4's theme namespaces (--color-*, --text-*, --radius-*…).
  const lines = flatten(tokens).map((token) => `  --${cssIdent(token.name)}: ${token.value};`);
  return `${header(tokens, (text) => `/* ${text} */`)}\n@import "tailwindcss";\n${fontImport(tokens)}\n@theme {\n${lines.join("\n")}\n}\n`;
}

export function toTailwindConfig(tokens: DesignTokens): string {
  const color = (value: Oklch) => formatColor(value, tokens.meta.colorFormat);
  const colors = Object.fromEntries([
    ...tokens.colors.map((token) => [
      token.name,
      token.shades.length
        ? { DEFAULT: color(token.value), ...Object.fromEntries(token.shades.map((s) => [s.step, color(s.value)])) }
        : color(token.value),
    ]),
    ...tokens.semantic.map((role) => [role.name, color(role.value)]),
  ]);
  const t = tokens.typography;
  const theme = {
    colors,
    ...(t
      ? {
          fontFamily: {
            heading: [t.heading.family, t.heading.category],
            body: [t.body.family, t.body.category],
          },
          fontSize: Object.fromEntries(
            t.steps.map((step) => [
              step.name,
              [
                step.clamp,
                { lineHeight: String(step.step > 0 ? t.rhythm.headingLineHeight : t.rhythm.bodyLineHeight) },
              ],
            ]),
          ),
        }
      : {}),
    ...(tokens.spacing.length ? { spacing: Object.fromEntries(tokens.spacing.map((s) => [s.name, px(s.px)])) } : {}),
    ...(tokens.radius.length ? { borderRadius: Object.fromEntries(tokens.radius.map((r) => [r.name, px(r.px)])) } : {}),
    ...(tokens.gradient ? { backgroundImage: { "gradient-primary": gradientCss(tokens.gradient) } } : {}),
  };
  return `${header(tokens, (text) => `// ${text}`)}
// Tailwind CSS v3 - for v4 use the CSS @theme export instead.
import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{ts,tsx,js,jsx,html}"],
  theme: {
    extend: ${JSON.stringify(theme, null, 2).replace(/\n/g, "\n    ")},
  },
} satisfies Config;
`;
}

/** Effects named `${kind}-${name}` (shadow-card, blur-glass) as a { name: value } scale. */
function effectScale(tokens: DesignTokens, kind: string, prefix: string): Record<string, string> {
  return Object.fromEntries(
    tokens.effects
      .filter((effect) => effect.name.startsWith(`${kind}-`))
      .map((effect) => [`${prefix}${effect.name.slice(kind.length + 1)}`, effect.value]),
  );
}

type Literal = string | number | Literal[] | { [key: string]: Literal };

/**
 * A value as a TypeScript literal with bare keys where they're valid, like hand-written config.
 * Objects and arrays that fit on one line (a `{ value: "#fff" }` token) stay on one line.
 */
function tsLiteral(value: Literal, indent = ""): string {
  if (typeof value !== "object") return JSON.stringify(value);
  const inner = `${indent}  `;
  const items = Array.isArray(value)
    ? value.map((item) => tsLiteral(item, inner))
    : Object.entries(value).map(([key, item]) => `${objectKey(key)}: ${tsLiteral(item, inner)}`);
  const [open, close] = Array.isArray(value) ? ["[", "]"] : ["{", "}"];
  const line = Array.isArray(value) ? `[${items.join(", ")}]` : items.length ? `{ ${items.join(", ")} }` : "{}";
  if (!line.includes("\n") && indent.length + line.length <= 80) return line;
  return `${open}\n${items.map((item) => `${inner}${item},`).join("\n")}\n${indent}${close}`;
}

/** Drops empty scales so the generated theme only lists what the tokens contain. */
const nonEmpty = (scales: Record<string, { [key: string]: Literal }>) =>
  Object.fromEntries(Object.entries(scales).filter(([, scale]) => Object.keys(scale).length > 0));

/**
 * UnoCSS (uno.config.ts): the tokens as a `presetWind3` theme. Colors with shades become
 * { DEFAULT, 50, 100… } objects so both `bg-indigo` and `bg-indigo-500` work, and the prefix
 * setting is prepended to every theme key (`bg-acme-indigo-500`).
 */
export function toUnoConfig(tokens: DesignTokens): string {
  const prefix = tokens.meta.prefix ? `${tokens.meta.prefix}-` : "";
  const color = (value: Oklch) => formatColor(value, tokens.meta.colorFormat);
  const t = tokens.typography;
  const theme = nonEmpty({
    colors: Object.fromEntries([
      ...tokens.colors.map((token) => [
        `${prefix}${token.name}`,
        token.shades.length
          ? { DEFAULT: color(token.value), ...Object.fromEntries(token.shades.map((s) => [s.step, color(s.value)])) }
          : color(token.value),
      ]),
      ...tokens.semantic.map((role) => [`${prefix}${role.name}`, color(role.value)]),
    ]),
    fontFamily: t
      ? {
          [`${prefix}heading`]: fontStack(t.heading.family, t.heading.category),
          [`${prefix}body`]: fontStack(t.body.family, t.body.category),
        }
      : {},
    fontSize: Object.fromEntries(
      (t?.steps ?? []).map((step) => [
        `${prefix}${step.name}`,
        [step.clamp, String(step.step > 0 ? t!.rhythm.headingLineHeight : t!.rhythm.bodyLineHeight)],
      ]),
    ),
    spacing: Object.fromEntries(tokens.spacing.map((s) => [`${prefix}${s.name}`, px(s.px)])),
    borderRadius: Object.fromEntries(tokens.radius.map((r) => [`${prefix}${r.name}`, px(r.px)])),
    boxShadow: effectScale(tokens, "shadow", prefix),
    blur: effectScale(tokens, "blur", prefix),
  });
  return `${header(tokens, (text) => `// ${text}`)}
import { defineConfig, presetWind3, type PresetWind3Theme } from "unocss";

export default defineConfig<PresetWind3Theme>({
  presets: [presetWind3()],
  theme: ${tsLiteral(theme, "  ")},
});
`;
}

/**
 * Base and semantic tokens in the `{ value }` shape Panda CSS and Chakra UI v3 share: colors,
 * fonts, font weights, font sizes, spacing, radii, shadows and blurs, plus semantic colors that
 * reference the base tokens (`{colors.indigo.300}`) with a `_dark` value for each role.
 */
function presetTokens(tokens: DesignTokens) {
  const prefix = tokens.meta.prefix ? `${tokens.meta.prefix}-` : "";
  const color = (value: Oklch) => formatColor(value, tokens.meta.colorFormat);
  const scale = (entries: [string, string][]) =>
    Object.fromEntries(entries.map(([key, value]) => [`${prefix}${key}`, { value }]));
  const effect = (kind: string) =>
    Object.fromEntries(Object.entries(effectScale(tokens, kind, prefix)).map(([key, value]) => [key, { value }]));
  const t = tokens.typography;

  const colors = Object.fromEntries(
    tokens.colors.map((token): [string, Literal] => [
      `${prefix}${token.name}`,
      token.shades.length
        ? {
            DEFAULT: { value: color(token.value) },
            ...Object.fromEntries(token.shades.map((s) => [s.step, { value: color(s.value) }])),
          }
        : { value: color(token.value) },
    ]),
  );
  // Roles point at the base tokens; the synthesized white or black has no base token, so it keeps its value.
  const reference = (entry: RoleColor) =>
    entry.color
      ? `{colors.${prefix}${entry.color}${entry.step !== undefined ? `.${entry.step}` : ""}}`
      : color(entry.value);
  const semanticColors = Object.fromEntries(
    tokens.semantic.flatMap((role) => {
      const light = roleColor(tokens, role.name);
      const dark = roleColor(tokens, role.name, true);
      return light && dark
        ? [[`${prefix}${role.name}`, { value: { base: reference(light), _dark: reference(dark) } }]]
        : [];
    }),
  );

  return {
    tokens: nonEmpty({
      colors,
      fonts: scale(
        t
          ? [
              ["heading", fontStack(t.heading.family, t.heading.category)],
              ["body", fontStack(t.body.family, t.body.category)],
            ]
          : [],
      ),
      fontWeights: scale(
        t
          ? [
              ["heading", String(t.rhythm.headingWeight)],
              ["body", String(t.rhythm.bodyWeight)],
            ]
          : [],
      ),
      fontSizes: scale((t?.steps ?? []).map((step) => [step.name, step.clamp])),
      spacing: scale(tokens.spacing.map((s) => [s.name, px(s.px)])),
      radii: scale(tokens.radius.map((r) => [r.name, px(r.px)])),
      shadows: effect("shadow"),
      blurs: effect("blur"),
    }),
    ...(tokens.semantic.length ? { semanticTokens: { colors: semanticColors } } : {}),
  };
}

/**
 * Panda CSS (panda.preset.ts): the shared preset tokens under `theme.extend`. List it in
 * `presets` after the base preset in panda.config.ts.
 */
export function toPandaPreset(tokens: DesignTokens): string {
  const preset = {
    name:
      tokens.meta.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "") || "designhub",
    theme: { extend: presetTokens(tokens) },
  };
  return `${header(tokens, (text) => `// ${text}`)}
import { definePreset } from "@pandacss/dev";

export default definePreset(${tsLiteral(preset)});
`;
}

/**
 * Chakra UI v3 (theme.ts): the shared preset tokens as a `defineConfig` theme, merged onto
 * Chakra's default config with `createSystem`. Pass it to `<ChakraProvider value={system}>`.
 */
export function toChakraTheme(tokens: DesignTokens): string {
  return `${header(tokens, (text) => `// ${text}`)}
import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react";

const config = defineConfig({
  theme: ${tsLiteral(presetTokens(tokens), "  ")},
});

export const system = createSystem(defaultConfig, config);

export default system;
`;
}

/**
 * Bootstrap 5 (_bootstrap-variables.scss): overrides for Bootstrap's `!default` variables, to
 * import before Bootstrap. Colors are always hex because Bootstrap runs them through Sass color
 * functions (tint-color, shade-color) that can't read oklch().
 */
export function toBootstrapVariables(tokens: DesignTokens): string {
  const hex = (name: string) => {
    const role = tokens.semantic.find((item) => item.name === name);
    return role ? toHex(role.value) : undefined;
  };
  const radius = (name: string) => {
    const step = tokens.radius.find((item) => item.name === name);
    return step ? px(step.px) : undefined;
  };
  // Bootstrap's $spacer is 1rem, the same as spacing-4 at the default base.
  const spacer = tokens.spacing.find((item) => item.name === "4");
  const t = tokens.typography;
  const vars: [string, string | number | undefined][] = [
    ["primary", hex("primary")],
    ["secondary", hex("accent")],
    ["body-color", hex("foreground")],
    ["body-bg", hex("background")],
    ["font-family-sans-serif", t ? fontStack(t.body.family, t.body.category) : undefined],
    ["headings-font-family", t ? fontStack(t.heading.family, t.heading.category) : undefined],
    ["font-weight-normal", t?.rhythm.bodyWeight],
    ["headings-font-weight", t?.rhythm.headingWeight],
    ["line-height-base", t?.rhythm.bodyLineHeight],
    ["headings-line-height", t?.rhythm.headingLineHeight],
    ["spacer", spacer && spacer.px > 0 ? px(spacer.px) : undefined],
    ["border-radius", radius("md")],
    ["border-radius-sm", radius("sm")],
    ["border-radius-lg", radius("lg")],
    ["border-radius-xl", radius("xl")],
    ["border-radius-xxl", radius("2xl")],
    ["box-shadow", tokens.effects.find((effect) => effect.name.startsWith("shadow-"))?.value],
  ];
  const lines = vars.flatMap(([name, value]) => (value === undefined ? [] : [`$${name}: ${value};`]));
  return `${header(tokens, (text) => `// ${text}`)}
// Bootstrap 5 variable overrides. Import this file before Bootstrap:
//   @import "bootstrap-variables";
//   @import "bootstrap/scss/bootstrap";
${lines.join("\n")}
`;
}

export function toReactTheme(tokens: DesignTokens): string {
  const groups = new Map<string, Record<string, string>>();
  flatten(tokens).forEach((token) => {
    const key = token.group === "semantic" ? "color" : token.group;
    const name = token.name.replace(/^(color|gradient|font|text|spacing|radius)-/, "");
    groups.set(key, { ...(groups.get(key) ?? {}), [name]: token.value });
  });
  const theme = Object.fromEntries(groups);
  return `${header(tokens, (text) => `// ${text}`)}
import type { CSSProperties } from "react";

export const theme = ${JSON.stringify(theme, null, 2)} as const;

export type Theme = typeof theme;

/** Spread onto a root element to expose the theme as CSS variables: <div style={themeVars}>. */
export const themeVars = Object.fromEntries(
  Object.entries(theme).flatMap(([group, values]) =>
    Object.entries(values).map(([name, value]) => [\`--\${group}-\${name}\`, value]),
  ),
) as CSSProperties;
`;
}

const styledGroups: Record<string, string> = {
  color: "colors",
  semantic: "colors",
  gradient: "gradients",
  font: "fonts",
  text: "fontSizes",
  spacing: "space",
  radius: "radii",
  effect: "effects",
};

// A hyphen between two digits becomes an underscore, so "indigo-2-50" (indigo-2, shade 50) and
// "indigo-250" stay different keys, matching the Swift and Flutter shade ids.
const camel = (value: string) =>
  value.replace(/(\d)-+(?=\d)/g, "$1_").replace(/-+([a-z0-9])/gi, (_, char: string) => char.toUpperCase());
const upperFirst = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);
const objectKey = (value: string) =>
  /^[A-Za-z_$][\w$]*$/.test(value) || /^(0|[1-9]\d*)$/.test(value) ? value : JSON.stringify(value);

/**
 * styled-components / Emotion: a typed theme object. Group names follow the styled-system
 * scales (colors, space, radii, fonts), and the prefix setting is prepended to every key.
 */
export function toStyledTheme(tokens: DesignTokens): string {
  const prefix = tokens.meta.prefix;
  const groups = new Map<string, Map<string, string>>();
  flatten(tokens).forEach((token) => {
    const group = styledGroups[token.group] ?? token.group;
    const base = camel(token.name.replace(/^(color|gradient|font|text|spacing|radius)-/, ""));
    const key = prefix ? `${camel(prefix)}${upperFirst(base.replace(/\./g, "_"))}` : base;
    groups.set(group, (groups.get(group) ?? new Map()).set(key, token.value));
  });
  const scales = [...groups]
    .map(([group, values]) => {
      const rows = [...values].map(([key, value]) => `    ${objectKey(key)}: ${JSON.stringify(value)},`);
      return `  ${group}: {\n${rows.join("\n")}\n  },`;
    })
    .join("\n");
  return `${header(tokens, (text) => `// ${text}`)}
import "styled-components";

export const theme = {
${scales}
} as const;

export type AppTheme = typeof theme;

declare module "styled-components" {
  export interface DefaultTheme extends AppTheme {}
}

// Emotion: replace the module augmentation above with
//   import "@emotion/react";
//   declare module "@emotion/react" { export interface Theme extends AppTheme {} }
// Then pass the theme to <ThemeProvider theme={theme}> and read props.theme in styled().
`;
}

/**
 * Plain JavaScript (ES module) for projects without TypeScript: one frozen object per scale
 * inside a frozen `tokens` object. Keys keep the token spelling ("indigo-2-50") so similar
 * names can't collide the way camelCase keys would, and start with the prefix setting.
 */
export function toJsModule(tokens: DesignTokens): string {
  const prefix = tokens.meta.prefix ? `${tokens.meta.prefix}-` : "";
  const groups = new Map<string, Map<string, string>>();
  flatten(tokens).forEach((token) => {
    const group = token.group === "semantic" ? "color" : token.group;
    const key = `${prefix}${token.name.replace(/^(color|gradient|font|text|spacing|radius)-/, "")}`;
    groups.set(group, (groups.get(group) ?? new Map()).set(key, token.value));
  });
  const scales = [...groups]
    .map(([group, values]) => {
      const rows = [...values].map(([key, value]) => `    ${objectKey(key)}: ${JSON.stringify(value)},`);
      return `  ${group}: Object.freeze({\n${rows.join("\n")}\n  }),`;
    })
    .join("\n");
  return `${header(tokens, (text) => `// ${text}`)}
export const tokens = Object.freeze({
${scales}
});

export default tokens;
`;
}

/** Vue 3: the theme object, an injection key and a plugin that exposes it as CSS variables. */
export function toVueTheme(tokens: DesignTokens): string {
  const groups = new Map<string, Record<string, string>>();
  flatten(tokens).forEach((token) => {
    const key = token.group === "semantic" ? "color" : token.group;
    const name = token.name.replace(/^(color|gradient|font|text|spacing|radius)-/, "");
    groups.set(key, { ...(groups.get(key) ?? {}), [name]: token.value });
  });
  const theme = Object.fromEntries(groups);
  return `${header(tokens, (text) => `// ${text}`)}
import { inject, type App, type InjectionKey } from "vue";

export const theme = ${JSON.stringify(theme, null, 2)} as const;

export type Theme = typeof theme;

export const themeKey: InjectionKey<Theme> = Symbol("theme");

/** CSS variables for the theme, e.g. --color-primary. */
export const themeVars: Record<string, string> = Object.fromEntries(
  Object.entries(theme).flatMap(([group, values]) =>
    Object.entries(values).map(([name, value]) => [\`--\${group}-\${name}\`, value]),
  ),
);

/** app.use(themePlugin) provides the theme and writes its variables onto :root. */
export const themePlugin = {
  install(app: App) {
    app.provide(themeKey, theme);
    if (typeof document !== "undefined") {
      Object.entries(themeVars).forEach(([name, value]) => document.documentElement.style.setProperty(name, value));
    }
  },
};

/** Read the theme inside a component: const theme = useTheme(). */
export function useTheme(): Theme {
  return inject(themeKey, theme);
}
`;
}

export function toJsonTokens(tokens: DesignTokens): string {
  const palette = tokens.colors.map((token) => ({
    name: token.name,
    color: token.value,
    shades: token.shades.map((shade) => ({ step: shade.step, color: shade.value })),
  }));
  const colors = colorTokens(
    palette,
    tokens.colors.some((token) => token.shades.length > 0),
    tokens.gradient ?? undefined,
  );
  const dimension = (value: number) => ({
    value: value >= 9999 ? 9999 : value / 16,
    unit: value >= 9999 ? "px" : "rem",
  });
  const t = tokens.typography;

  const document = {
    $description: `${tokens.meta.name} - generated by DesignHub on ${tokens.meta.generatedAt}`,
    ...colors,
    ...(tokens.semantic.length
      ? {
          semantic: Object.fromEntries(
            tokens.semantic.map((role) => {
              const source = tokens.colors.find((color) => color.name === role.ref);
              // Aliases only resolve to palette colors; synthesized white/black are written as values.
              const $value = source
                ? `{color.${role.ref}${source.shades.length ? ".DEFAULT" : ""}}`
                : {
                    colorSpace: "oklch",
                    components: [role.value.l, role.value.c, role.value.h],
                    hex: toHex(role.value),
                  };
              return [role.name, { $type: "color", $value }];
            }),
          ),
        }
      : {}),
    ...(t
      ? {
          font: {
            family: {
              heading: { $type: "fontFamily", $value: [t.heading.family, t.heading.category] },
              body: { $type: "fontFamily", $value: [t.body.family, t.body.category] },
            },
            weight: {
              heading: { $type: "fontWeight", $value: t.rhythm.headingWeight },
              body: { $type: "fontWeight", $value: t.rhythm.bodyWeight },
            },
            size: Object.fromEntries(
              t.steps.map((step) => [
                step.name,
                {
                  $type: "dimension",
                  $value: dimension(step.maxPx),
                  $extensions: { "dev.designhub.fluid": { min: dimension(step.minPx), css: step.clamp } },
                },
              ]),
            ),
          },
        }
      : {}),
    ...(tokens.spacing.length
      ? {
          spacing: Object.fromEntries(
            tokens.spacing.map((s) => [s.name, { $type: "dimension", $value: dimension(s.px) }]),
          ),
        }
      : {}),
    ...(tokens.radius.length
      ? {
          radius: Object.fromEntries(
            tokens.radius.map((r) => [r.name, { $type: "dimension", $value: dimension(r.px) }]),
          ),
        }
      : {}),
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

export function tokenFormats(tokens: DesignTokens): ExportFormat[] {
  return [
    { id: "css", label: "CSS variables", filename: "tokens.css", language: "css", code: toCss(tokens) },
    { id: "scss", label: "SCSS", filename: "_tokens.scss", language: "scss", code: toScss(tokens) },
    {
      id: "sass-map",
      label: "Sass map",
      filename: "_tokens-map.scss",
      language: "scss",
      code: toSassMap(tokens),
    },
    { id: "less", label: "Less", filename: "tokens.less", language: "css", code: toLess(tokens) },
    { id: "stylus", label: "Stylus", filename: "tokens.styl", language: "css", code: toStylus(tokens) },
    { id: "android", label: "Android XML", filename: "colors.xml", language: "xml", code: toAndroidColors(tokens) },
    { id: "tailwind-v4", label: "Tailwind v4", filename: "theme.css", language: "css", code: toTailwindV4(tokens) },
    {
      id: "tailwind-config",
      label: "Tailwind config",
      filename: "tailwind.config.ts",
      language: "ts",
      code: toTailwindConfig(tokens),
    },
    { id: "unocss", label: "UnoCSS", filename: "uno.config.ts", language: "ts", code: toUnoConfig(tokens) },
    { id: "panda", label: "Panda CSS", filename: "panda.preset.ts", language: "ts", code: toPandaPreset(tokens) },
    { id: "chakra", label: "Chakra UI", filename: "theme.ts", language: "ts", code: toChakraTheme(tokens) },
    {
      id: "bootstrap",
      label: "Bootstrap",
      filename: "_bootstrap-variables.scss",
      language: "scss",
      code: toBootstrapVariables(tokens),
    },
    { id: "js", label: "JavaScript", filename: "tokens.mjs", language: "js", code: toJsModule(tokens) },
    { id: "react", label: "React theme", filename: "theme.ts", language: "ts", code: toReactTheme(tokens) },
    {
      id: "styled",
      label: "styled-components",
      filename: "styled-theme.ts",
      language: "ts",
      code: toStyledTheme(tokens),
    },
    { id: "vue", label: "Vue theme", filename: "theme.ts", language: "ts", code: toVueTheme(tokens) },
    { id: "flutter", label: "Flutter", filename: "theme.dart", language: "dart", code: toFlutterTheme(tokens) },
    { id: "swiftui", label: "SwiftUI", filename: "Theme.swift", language: "swift", code: toSwiftUITheme(tokens) },
    { id: "compose", label: "Jetpack Compose", filename: "Theme.kt", language: "kotlin", code: toComposeTheme(tokens) },
    { id: "json", label: "JSON tokens", filename: "tokens.json", language: "json", code: toJsonTokens(tokens) },
    { id: "yaml", label: "YAML", filename: "tokens.yaml", language: "yaml", code: toYaml(tokens) },
    {
      id: "tokens-studio",
      label: "Tokens Studio",
      filename: "tokens-studio.json",
      language: "json",
      code: toTokensStudio(tokens),
    },
  ];
}

export function paletteHexes(tokens: DesignTokens): { name: string; hex: string }[] {
  return tokens.colors.map((token) => ({ name: token.name, hex: toHex(token.value) }));
}
