import { contrastRatio, toHex, toRgb } from "@/lib/color/color";
import { siteConfig } from "@/lib/site";
import type { Oklch } from "@/types/color";
import type { DesignTokens } from "@/types/tokens";

/**
 * Generators for native and design-tool formats: Flutter, SwiftUI, Jetpack Compose and Tokens
 * Studio for Figma.
 * Like the web formats they read only `DesignTokens`, so every export describes the same system.
 */

const headerText = (tokens: DesignTokens) =>
  `${tokens.meta.name} - design tokens generated by DesignHub (${siteConfig.github})`;

/** "Acme Labs" -> "AcmeLabs"; falls back to "Brand" for names without letters. */
function pascal(name: string): string {
  const words = name.match(/[A-Za-z0-9]+/g) ?? [];
  const joined = words.map((word) => word[0]!.toUpperCase() + word.slice(1)).join("");
  return /^[A-Za-z]/.test(joined) ? joined : `Brand${joined}`;
}

/** "indigo-500" -> "indigo500", "0.5" -> "s0_5"; identifiers can't start with a digit. */
function ident(name: string, digitPrefix: string): string {
  const parts = name
    .replace(/\./g, "_")
    .split(/[^A-Za-z0-9_]+/)
    .filter(Boolean);
  const camel = parts.map((part, i) => (i === 0 ? part : part[0]!.toUpperCase() + part.slice(1))).join("");
  return /^[0-9]/.test(camel) ? `${digitPrefix}${camel}` : camel;
}

/** Collects unique identifiers in order, dropping later duplicates. */
function unique<T extends { id: string }>(items: T[]): T[] {
  const seen = new Set<string>();
  return items.filter((item) => (seen.has(item.id) ? false : (seen.add(item.id), true)));
}

/** `key` names the source token ("indigo", "indigo/250", "role:primary") so a format can refer back to it. */
type ColorEntry = { id: string; key: string; value: Oklch; comment?: string };

function colorEntries(tokens: DesignTokens, digitPrefix: string): ColorEntry[] {
  const list: ColorEntry[] = [];
  tokens.colors.forEach((color) => {
    list.push({ id: ident(color.name, digitPrefix), key: color.name, value: color.value });
    // The underscore keeps "indigo-2" shade 50 (indigo2_50) apart from "indigo" shade 250 (indigo_250).
    color.shades.forEach((shade) =>
      list.push({
        id: ident(`${color.name}_${shade.step}`, digitPrefix),
        key: `${color.name}/${shade.step}`,
        value: shade.value,
      }),
    );
  });
  tokens.semantic.forEach((role) =>
    list.push({
      id: ident(role.name, digitPrefix),
      key: `role:${role.name}`,
      value: role.value,
      comment: `semantic, ${role.ref}`,
    }),
  );
  return unique(list);
}

/**
 * Where a semantic role's color comes from in light or dark mode. `role` is the semantic role
 * that supplies it, `color` the palette color it points at (missing for the synthesized white
 * and black) and `step` the shade, when dark mode lifts the role to one.
 */
export type RoleColor = { role: string; color?: string; step?: number; value: Oklch };

/**
 * A semantic role in light or dark mode. Dark mode swaps the light background and the dark
 * foreground, and lifts every other role to its palette color's 300 (or 200) shade so it stays
 * readable on the dark background. Compose and the Panda CSS and Chakra UI exports share this.
 */
export function roleColor(tokens: DesignTokens, roleName: string, dark = false): RoleColor | undefined {
  const swap: Record<string, string> = { background: "foreground", foreground: "background" };
  const swapped = dark ? swap[roleName] : undefined;
  const item = tokens.semantic.find((entry) => entry.name === (swapped ?? roleName));
  if (!item) return undefined;
  const source = tokens.colors.find((entry) => entry.name === item.ref);
  const lift = dark && !swapped ? source : undefined;
  const shade = lift?.shades.find((s) => s.step === 300) ?? lift?.shades.find((s) => s.step === 200);
  return { role: item.name, color: source?.name, step: shade?.step, value: shade?.value ?? item.value };
}

const px = (value: number) => (value >= 9999 ? 9999 : Math.round(value * 100) / 100);
const weight = (value: number) => Math.min(900, Math.max(100, Math.round(value / 100) * 100));

/* ------------------------------------------------------------------ Flutter */

/** Material text theme slots for each step of the type scale, smallest to largest. */
const flutterSlots: Record<string, string> = {
  xs: "labelSmall",
  sm: "bodySmall",
  base: "bodyMedium",
  lg: "bodyLarge",
  xl: "titleLarge",
  "2xl": "headlineSmall",
  "3xl": "headlineMedium",
  "4xl": "headlineLarge",
  "5xl": "displaySmall",
  "6xl": "displayMedium",
};

const dartString = (value: string) => `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;

/** `Color(0xAARRGGBB)`: the same constructor spelling in Dart and Kotlin. */
function argbColor(value: Oklch): string {
  const { r, g, b, alpha } = toRgb(value);
  const hex = [Math.round(alpha * 255), r, g, b].map((channel) => channel.toString(16).padStart(2, "0")).join("");
  return `Color(0x${hex.toUpperCase()})`;
}

/** Flutter: color, spacing, radius and font constants plus a Material 3 `ThemeData`. */
export function toFlutterTheme(tokens: DesignTokens): string {
  const name = pascal(tokens.meta.name);
  const lower = name[0]!.toLowerCase() + name.slice(1);
  const colors = colorEntries(tokens, "c");
  const primary = tokens.semantic.find((role) => role.name === "primary")?.value ?? tokens.colors[0]?.value;
  const t = tokens.typography;

  const colorLines = colors
    .map(
      (color) =>
        `  static const ${color.id} = ${argbColor(color.value)};${color.comment ? ` // ${color.comment}` : ""}`,
    )
    .join("\n");
  const doubles = (items: { name: string; px: number }[]) =>
    unique(items.map((item) => ({ id: ident(item.name, "s"), px: item.px })))
      .map((item) => `  static const double ${item.id} = ${px(item.px)};`)
      .join("\n");
  const textStyles = t
    ? t.steps
        .filter((step) => flutterSlots[step.name])
        .map((step) => {
          const heading = step.maxPx >= 24;
          const family = heading ? `${name}Fonts.heading` : `${name}Fonts.body`;
          const w = weight(heading ? t.rhythm.headingWeight : t.rhythm.bodyWeight);
          const height = heading ? t.rhythm.headingLineHeight : t.rhythm.bodyLineHeight;
          return `    ${flutterSlots[step.name]}: TextStyle(fontFamily: ${family}, fontSize: ${px(step.maxPx)}, fontWeight: FontWeight.w${w}, height: ${height}),`;
        })
        .join("\n")
    : "";

  return `// ${headerText(tokens)}
// Add the fonts to pubspec.yaml (or use the google_fonts package) for the families below to load.
import 'package:flutter/material.dart';

class ${name}Colors {
  ${name}Colors._();
${colorLines}
}

class ${name}Spacing {
  ${name}Spacing._();
${doubles(tokens.spacing)}
}

class ${name}Radius {
  ${name}Radius._();
${doubles(tokens.radius)}
}
${
  t
    ? `
class ${name}Fonts {
  ${name}Fonts._();
  static const heading = ${dartString(t.heading.family)};
  static const body = ${dartString(t.body.family)};
}
`
    : ""
}
ThemeData ${lower}Theme({Brightness brightness = Brightness.light}) {
  return ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(seedColor: ${primary ? argbColor(primary) : "Colors.indigo"}, brightness: brightness),${t ? `\n    fontFamily: ${name}Fonts.body,` : ""}
    cardTheme: CardThemeData(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(${px(tokens.radius.find((r) => r.name === "lg")?.px ?? 12)}))),${
      textStyles ? `\n    textTheme: const TextTheme(\n${textStyles}\n    ),` : ""
    }
  );
}
`;
}

/* ------------------------------------------------------------------ SwiftUI */

const round3 = (value: number) => Math.round(value * 1000) / 1000;
const swiftString = (value: string) => `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

function swiftColor(value: Oklch): string {
  const { r, g, b, alpha } = toRgb(value);
  const channels = `red: ${round3(r / 255)}, green: ${round3(g / 255)}, blue: ${round3(b / 255)}`;
  return `Color(${channels}${alpha < 1 ? `, opacity: ${round3(alpha)}` : ""})`;
}

/**
 * SwiftUI: colors as `Color` extensions (prefixed with the brand, so they never clash with
 * system colors such as `Color.indigo`), plus spacing, radius and font helpers.
 */
export function toSwiftUITheme(tokens: DesignTokens): string {
  const name = pascal(tokens.meta.name);
  const prefix = name[0]!.toLowerCase() + name.slice(1);
  // Prefixing upper-cases the first letter, so "indigo" and "Indigo" are de-duplicated again after it.
  const colors = unique(
    colorEntries(tokens, "c").map((color) => ({
      ...color,
      id: `${prefix}${color.id[0]!.toUpperCase()}${color.id.slice(1)}`,
    })),
  );
  const t = tokens.typography;
  const lets = (items: { name: string; px: number }[]) =>
    unique(items.map((item) => ({ id: ident(item.name, "s"), px: item.px })))
      .map((item) => `    static let ${item.id}: CGFloat = ${px(item.px)}`)
      .join("\n");

  const fonts = t
    ? `
enum ${name}Font {
    static let headingFamily = ${swiftString(t.heading.family)}
    static let bodyFamily = ${swiftString(t.body.family)}

    /// Font files must be added to the app target and listed under UIAppFonts in Info.plist.
    static func heading(_ size: CGFloat) -> Font { .custom(headingFamily, size: size).weight(.${swiftWeight(t.rhythm.headingWeight)}) }
    static func body(_ size: CGFloat) -> Font { .custom(bodyFamily, size: size) }

${unique(t.steps.map((step) => ({ id: ident(step.name, "size"), step })))
  .map(({ id, step }) => `    static let ${id} = ${step.maxPx >= 24 ? "heading" : "body"}(${px(step.maxPx)})`)
  .join("\n")}
}
`
    : "";

  return `// ${headerText(tokens)}
import SwiftUI

extension Color {
${colors.map((color) => `    static let ${color.id} = ${swiftColor(color.value)}${color.comment ? ` // ${color.comment}` : ""}`).join("\n")}
}

enum ${name}Spacing {
${lets(tokens.spacing)}
}

enum ${name}Radius {
${lets(tokens.radius)}
}
${fonts}`;
}

function swiftWeight(value: number): string {
  const names: Record<number, string> = {
    100: "ultraLight",
    200: "thin",
    300: "light",
    400: "regular",
    500: "medium",
    600: "semibold",
    700: "bold",
    800: "heavy",
    900: "black",
  };
  return names[weight(value)] ?? "regular";
}

/* ---------------------------------------------------------- Jetpack Compose */

const kotlinString = (value: string) => `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;

/**
 * Kotlin keywords are all lowercase, so PascalCase members never clash with one. A member named
 * "Color" would shadow the Compose constructor inside the colors object, so it gets an underscore.
 */
function kotlinMember(id: string): string {
  const member = `${id[0]!.toUpperCase()}${id.slice(1)}`;
  return member === "Color" ? "Color_" : member;
}

const dp = (value: number) => `${px(value)}.dp`;
const upperFirst = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);
const white: Oklch = { l: 1, c: 0, h: 0, alpha: 1 };
const black: Oklch = { l: 0, c: 0, h: 0, alpha: 1 };

/** Material 3 shape slots, smallest to largest, and the radius step each one uses. */
const composeShapes: [slot: string, radius: string][] = [
  ["extraSmall", "sm"],
  ["small", "md"],
  ["medium", "lg"],
  ["large", "xl"],
  ["extraLarge", "2xl"],
];

/**
 * Jetpack Compose (Material 3): a colors object, light and dark `ColorScheme`s from the semantic
 * roles, spacing and radius `Dp` values, `Shapes` and a `<Brand>Theme` composable. Color members
 * reuse the SwiftUI and Flutter identifiers (indigo_250 vs indigo2_50) in PascalCase.
 */
export function toComposeTheme(tokens: DesignTokens): string {
  // A brand called "Material" would declare its own MaterialTheme next to the Compose one.
  const name = pascal(tokens.meta.name) === "Material" ? "MaterialBrand" : pascal(tokens.meta.name);
  const colors = unique(colorEntries(tokens, "c").map((color) => ({ ...color, id: kotlinMember(color.id) })));
  const members = new Map(colors.map((color) => [color.key, `${name}Colors.${color.id}`]));
  // Refer to the colors object where the token survived de-duplication, otherwise inline the value.
  const color = (key: string, value: Oklch) => members.get(key) ?? argbColor(value);
  const on = (value: Oklch) =>
    contrastRatio(value, white) >= contrastRatio(value, black) ? "Color.White" : "Color.Black";
  const dps = (items: { name: string; px: number }[]) =>
    unique(items.map((item) => ({ id: kotlinMember(ident(item.name, "s")), name: item.name, px: item.px })));
  const spacing = dps(tokens.spacing);
  const radius = dps(tokens.radius);
  const body = (lines: string[]) => (lines.length ? `\n${lines.join("\n")}\n` : "");
  const t = tokens.typography;

  /** A semantic role as a color reference: the lifted shade in dark mode, otherwise the role itself. */
  const role = (roleName: string, dark: boolean) => {
    const entry = roleColor(tokens, roleName, dark);
    if (!entry) return undefined;
    return entry.step !== undefined
      ? { code: color(`${entry.color}/${entry.step}`, entry.value), value: entry.value }
      : { code: color(`role:${entry.role}`, entry.value), value: entry.value };
  };
  const scheme = (dark: boolean) => {
    const lines: string[] = [];
    const brand = (slot: string, roleName: string) => {
      const entry = role(roleName, dark);
      if (entry) lines.push(`    ${slot} = ${entry.code},`, `    on${upperFirst(slot)} = ${on(entry.value)},`);
    };
    brand("primary", "primary");
    brand("secondary", "accent");
    const background = role("background", dark);
    const foreground = role("foreground", dark);
    if (background) lines.push(`    background = ${background.code},`, `    surface = ${background.code},`);
    if (foreground) lines.push(`    onBackground = ${foreground.code},`, `    onSurface = ${foreground.code},`);
    return lines;
  };
  const shapes = composeShapes.flatMap(([slot, step]) => {
    const item = radius.find((entry) => entry.name === step);
    return item ? [`    ${slot} = RoundedCornerShape(${name}Radius.${item.id}),`] : [];
  });

  return `// ${headerText(tokens)}
// Change the package to match your app. Requires Compose Material 3.
package com.example.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object ${name}Colors {${body(
    colors.map(
      (entry) => `    val ${entry.id} = ${argbColor(entry.value)}${entry.comment ? ` // ${entry.comment}` : ""}`,
    ),
  )}}

object ${name}Spacing {${body(spacing.map((item) => `    val ${item.id} = ${dp(item.px)}`))}}

object ${name}Radius {${body(radius.map((item) => `    val ${item.id} = ${dp(item.px)}`))}}
${
  t
    ? `
/** Family names: load them with downloadable Google Fonts or add the files to res/font. */
object ${name}Fonts {
    const val Heading = ${kotlinString(t.heading.family)}
    const val Body = ${kotlinString(t.body.family)}
}
`
    : ""
}
val ${name}LightColorScheme = lightColorScheme(${body(scheme(false))})

val ${name}DarkColorScheme = darkColorScheme(${body(scheme(true))})

val ${name}Shapes = Shapes(${body(shapes)})

@Composable
fun ${name}Theme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    MaterialTheme(
        colorScheme = if (darkTheme) ${name}DarkColorScheme else ${name}LightColorScheme,
        shapes = ${name}Shapes,
        content = content,
    )
}
`;
}

/* ------------------------------------------------------------ Tokens Studio */

type StudioToken = { value: string | Record<string, string>; type: string; description?: string };
type StudioGroup = { [key: string]: StudioToken | StudioGroup };

const percent = (value: number) => `${Math.round(value * 1000) / 10}%`;

/**
 * Tokens Studio for Figma: one "global" set with colors, semantic aliases, spacing, radii and
 * typography, in the plugin's JSON format (load it with Tools, Load from file).
 */
export function toTokensStudio(tokens: DesignTokens): string {
  const color: StudioGroup = {};
  tokens.colors.forEach((token) => {
    const group: StudioGroup = { base: { value: toHex(token.value), type: "color" } };
    token.shades.forEach((shade) => (group[String(shade.step)] = { value: toHex(shade.value), type: "color" }));
    color[token.name] = group;
  });
  const semantic: StudioGroup = {};
  tokens.semantic.forEach((role) => {
    const inPalette = tokens.colors.some((token) => token.name === role.ref);
    semantic[role.name] = { value: inPalette ? `{color.${role.ref}.base}` : toHex(role.value), type: "color" };
  });
  const dimension = (items: { name: string; px: number }[], type: string): StudioGroup =>
    Object.fromEntries(items.map((item) => [item.name.replace(/\./g, "_"), { value: String(px(item.px)), type }]));

  const global: StudioGroup = {
    color,
    semantic,
    spacing: dimension(tokens.spacing, "spacing"),
    borderRadius: dimension(tokens.radius, "borderRadius"),
  };

  const t = tokens.typography;
  if (t) {
    global.fontFamilies = {
      heading: { value: t.heading.family, type: "fontFamilies" },
      body: { value: t.body.family, type: "fontFamilies" },
    };
    global.fontWeights = {
      heading: { value: String(t.rhythm.headingWeight), type: "fontWeights" },
      body: { value: String(t.rhythm.bodyWeight), type: "fontWeights" },
    };
    global.lineHeights = {
      heading: { value: percent(t.rhythm.headingLineHeight), type: "lineHeights" },
      body: { value: percent(t.rhythm.bodyLineHeight), type: "lineHeights" },
    };
    global.letterSpacing = {
      heading: { value: percent(t.rhythm.headingTracking), type: "letterSpacing" },
      body: { value: percent(t.rhythm.bodyTracking), type: "letterSpacing" },
    };
    global.fontSizes = Object.fromEntries(
      t.steps.map((step) => [step.name, { value: String(px(step.maxPx)), type: "fontSizes" }]),
    );
    global.typography = Object.fromEntries(
      t.steps.map((step) => {
        const role = step.maxPx >= 24 ? "heading" : "body";
        return [
          step.name,
          {
            value: {
              fontFamily: `{fontFamilies.${role}}`,
              fontWeight: `{fontWeights.${role}}`,
              lineHeight: `{lineHeights.${role}}`,
              letterSpacing: `{letterSpacing.${role}}`,
              fontSize: `{fontSizes.${step.name}}`,
            },
            type: "typography",
          },
        ];
      }),
    );
  }

  const document = {
    global,
    $themes: [],
    $metadata: { tokenSetOrder: ["global"] },
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}
