import { CREDIT_TEXT } from "@/lib/export/credit";
import { toHex, toRgb } from "@/lib/color/color";
import type { DesignTokens } from "@/types/tokens";

type Rgb = { r: number; g: number; b: number };

/**
 * Builds a printable style guide PDF with pdf-lib (loaded on demand).
 * Uses standard PDF fonts; the chosen Google Fonts are listed by name.
 */
export async function buildStyleGuidePdf(tokens: DesignTokens, snapshot?: Uint8Array): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${tokens.meta.name} style guide`);
  pdf.setProducer("DesignHub");
  pdf.setCreator(CREDIT_TEXT);

  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const mono = await pdf.embedFont(StandardFonts.Courier);

  const width = 842; // A4 landscape
  const height = 595;
  const margin = 48;
  const ink = rgb(0.09, 0.09, 0.11);
  const muted = rgb(0.45, 0.45, 0.5);
  const toPdf = ({ r, g, b }: Rgb) => rgb(r / 255, g / 255, b / 255);

  let page = pdf.addPage([width, height]);
  let y = height - margin;

  const newPage = () => {
    page = pdf.addPage([width, height]);
    y = height - margin;
  };
  const ensure = (space: number) => {
    if (y - space < margin) newPage();
  };
  const heading = (text: string) => {
    ensure(48);
    page.drawText(text.toUpperCase(), { x: margin, y, size: 9, font: bold, color: muted });
    y -= 22;
  };

  // Cover
  page.drawText(tokens.meta.name, { x: margin, y: y - 24, size: 32, font: bold, color: ink });
  page.drawText(`Style guide · generated by DesignHub · ${new Date(tokens.meta.generatedAt).toLocaleDateString()}`, {
    x: margin,
    y: y - 48,
    size: 10,
    font: regular,
    color: muted,
  });
  y -= 84;

  if (snapshot) {
    const image = await pdf.embedPng(snapshot);
    const scale = Math.min((width - margin * 2) / image.width, (y - margin) / image.height, 1);
    page.drawImage(image, {
      x: margin,
      y: y - image.height * scale,
      width: image.width * scale,
      height: image.height * scale,
    });
  }
  newPage();

  if (tokens.colors.length) {
    heading("Colors");
    const columns = Math.min(tokens.colors.length, 6);
    const swatchWidth = (width - margin * 2 - (columns - 1) * 12) / columns;
    tokens.colors.forEach((token, index) => {
      if (index > 0 && index % columns === 0) y -= 110;
      ensure(110);
      const x = margin + (index % columns) * (swatchWidth + 12);
      page.drawRectangle({ x, y: y - 64, width: swatchWidth, height: 64, color: toPdf(toRgb(token.value)) });
      page.drawText(token.name, { x, y: y - 80, size: 10, font: bold, color: ink });
      page.drawText(toHex(token.value).toUpperCase(), { x, y: y - 94, size: 9, font: mono, color: muted });
    });
    y -= 118;

    const shaded = tokens.colors.filter((token) => token.shades.length);
    if (shaded.length) {
      heading("Shades");
      shaded.forEach((token) => {
        ensure(44);
        page.drawText(token.name, { x: margin, y: y - 14, size: 9, font: bold, color: ink });
        const cell = (width - margin * 2 - 80) / token.shades.length;
        token.shades.forEach((shade, index) => {
          const x = margin + 80 + index * cell;
          page.drawRectangle({ x, y: y - 24, width: cell, height: 24, color: toPdf(toRgb(shade.value)) });
          page.drawText(String(shade.step), { x: x + 2, y: y - 34, size: 6, font: regular, color: muted });
        });
        y -= 44;
      });
      y -= 12;
    }
  }

  const t = tokens.typography;
  if (t) {
    heading("Typography");
    ensure(60);
    page.drawText(`Heading: ${t.heading.family} · ${t.rhythm.headingWeight}`, {
      x: margin,
      y,
      size: 12,
      font: bold,
      color: ink,
    });
    page.drawText(`Body: ${t.body.family} · ${t.rhythm.bodyWeight}`, {
      x: margin + 360,
      y,
      size: 12,
      font: regular,
      color: ink,
    });
    y -= 24;
    t.steps.forEach((step) => {
      const size = Math.min(step.maxPx, 44);
      ensure(size + 16);
      page.drawText(step.name, { x: margin, y: y - size * 0.8, size: 9, font: mono, color: muted });
      page.drawText(`${step.minPx}–${step.maxPx}px`, {
        x: margin + 44,
        y: y - size * 0.8,
        size: 8,
        font: mono,
        color: muted,
      });
      page.drawText("Design with intent", {
        x: margin + 140,
        y: y - size * 0.8,
        size,
        font: step.step > 0 ? bold : regular,
        color: ink,
      });
      y -= size + 14;
    });
    y -= 8;
  }

  if (tokens.spacing.length || tokens.radius.length) {
    heading("Spacing & radius");
    ensure(90);
    let x = margin;
    tokens.spacing.forEach((step) => {
      const size = Math.max(2, Math.min(step.px, 64));
      page.drawRectangle({ x, y: y - size, width: size, height: size, color: rgb(0.39, 0.4, 0.95) });
      page.drawText(step.name, { x, y: y - 76, size: 7, font: mono, color: muted });
      x += Math.max(size, 20) + 10;
    });
    y -= 100;
    ensure(80);
    x = margin;
    tokens.radius.forEach((step) => {
      const radius = Math.min(step.px, 24);
      page.drawSvgPath(
        `M ${radius} 0 H ${48 - radius} Q 48 0 48 ${radius} V ${48 - radius} Q 48 48 ${48 - radius} 48 H ${radius} Q 0 48 0 ${48 - radius} V ${radius} Q 0 0 ${radius} 0 Z`,
        { x, y, borderColor: ink, borderWidth: 1 },
      );
      page.drawText(step.name, { x, y: y - 62, size: 7, font: mono, color: muted });
      x += 68;
    });
  }

  return pdf.save();
}
