import { splitIconId } from "@/lib/icons/iconify";
import { buildIconSvg } from "@/lib/icons/svg";
import { svgCssUrl } from "@/lib/svg/data-uri";
import type { ExportFormat } from "@/types/export";
import type { IconData, IconId, IconStyle } from "@/types/icons";

/** "tabler:brand-github" → "BrandGithubIcon" */
export function componentName(id: IconId): string {
  const { name } = splitIconId(id);
  const pascal = name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  const safe = /^[0-9]/.test(pascal) ? `Icon${pascal}` : pascal;
  return `${safe}Icon`;
}

/** Converts SVG markup attributes to their JSX spelling (stroke-width → strokeWidth). */
export function svgToJsx(svg: string): string {
  return svg
    .replace(/\s(class)=/g, " className=")
    .replace(
      /\s(xlink):([a-z]+)=/g,
      (_, ns: string, attr: string) => ` ${ns}${attr.charAt(0).toUpperCase()}${attr.slice(1)}=`,
    )
    .replace(/\s([a-z]+(?:-[a-z]+)+)=/g, (match, attr: string) =>
      attr.startsWith("data-") || attr.startsWith("aria-")
        ? match
        : ` ${attr.replace(/-([a-z])/g, (_: string, letter: string) => letter.toUpperCase())}=`,
    );
}

function reactComponent(id: IconId, icon: IconData, style: IconStyle): string {
  const name = componentName(id);
  const svg = buildIconSvg(icon, { ...style, size: 24 }, { uniqueIds: true });
  const inner = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  return `import type { SVGProps } from "react";

// ${id} - generated by DesignHub. Size with font-size or width/height; color inherits currentColor.
export function ${name}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 1000 1000" aria-hidden="true" {...props}>
      ${svgToJsx(inner)}
    </svg>
  );
}
`;
}

/** Vue 3 single-file component. Attributes keep their SVG spelling; $attrs (class, style, size) go on the <svg>. */
function vueComponent(id: IconId, icon: IconData, style: IconStyle): string {
  const name = componentName(id);
  const svg = buildIconSvg(icon, { ...style, size: 24 }, { uniqueIds: true });
  const inner = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  return `<script setup lang="ts">
// ${id} - generated by DesignHub. Size with font-size or width/height; color inherits currentColor.
defineOptions({ name: "${name}", inheritAttrs: false });
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 1000 1000" aria-hidden="true" v-bind="$attrs">
    ${inner}
  </svg>
</template>
`;
}

/**
 * Svelte 5 component. Extra props (class, style, width) are spread onto the <svg> with {...rest}.
 * Braces start an expression in Svelte markup, so any in the icon body are written as entities.
 */
function svelteComponent(id: IconId, icon: IconData, style: IconStyle): string {
  const svg = buildIconSvg(icon, { ...style, size: 24 }, { uniqueIds: true });
  const inner = svg
    .replace(/^<svg[^>]*>/, "")
    .replace(/<\/svg>$/, "")
    .replace(/[{}]/g, (brace) => (brace === "{" ? "&#123;" : "&#125;"));
  return `<script lang="ts">
  // ${id} - generated by DesignHub. Size with font-size or width/height; color inherits currentColor.
  import type { SVGAttributes } from "svelte/elements";

  let { ...rest }: SVGAttributes<SVGSVGElement> = $props();
</script>

<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 1000 1000" aria-hidden="true" {...rest}>
  ${inner}
</svg>
`;
}

function cssDataUri(icon: IconData, style: IconStyle): string {
  // currentColor has no meaning inside a background image, so use a mask for monochrome icons.
  const svg = buildIconSvg(icon, { ...style, size: 24, color: style.color === "currentColor" ? "#000" : style.color });
  const uri = svgCssUrl(svg);
  return style.color === "currentColor"
    ? `.icon {\n  display: inline-block;\n  width: 1em;\n  height: 1em;\n  background-color: currentColor;\n  mask: ${uri} no-repeat center / contain;\n}\n`
    : `.icon {\n  display: inline-block;\n  width: 1em;\n  height: 1em;\n  background: ${uri} no-repeat center / contain;\n}\n`;
}

export function iconExports(id: IconId, icon: IconData, style: IconStyle): ExportFormat[] {
  const { name } = splitIconId(id);
  return [
    {
      id: "svg",
      label: "SVG",
      filename: `${name}.svg`,
      language: "svg",
      code: `${buildIconSvg(icon, style, { uniqueIds: true })}\n`,
    },
    {
      id: "react",
      label: "React",
      filename: `${componentName(id)}.tsx`,
      language: "tsx",
      code: reactComponent(id, icon, style),
    },
    {
      id: "vue",
      label: "Vue",
      filename: `${componentName(id)}.vue`,
      language: "vue",
      code: vueComponent(id, icon, style),
    },
    {
      id: "svelte",
      label: "Svelte",
      filename: `${componentName(id)}.svelte`,
      language: "svelte",
      code: svelteComponent(id, icon, style),
    },
    { id: "css", label: "CSS", filename: `${name}.css`, language: "css", code: cssDataUri(icon, style) },
  ];
}
