import type { IconId } from "@/types/icons";

export type IconTopic = { id: string; label: string; icons: IconId[] };

/**
 * Curated starter sets, shown before you search. Every id is checked against the Iconify
 * API. Mostly Lucide, Tabler and Phosphor (consistent line icons) plus Simple Icons for brands.
 */
export const iconTopics: IconTopic[] = [
  {
    id: "essentials",
    label: "UI essentials",
    icons: [
      "lucide:house",
      "lucide:search",
      "lucide:settings",
      "lucide:user",
      "lucide:bell",
      "lucide:menu",
      "lucide:x",
      "lucide:check",
      "lucide:plus",
      "lucide:minus",
      "lucide:trash-2",
      "lucide:pencil",
      "lucide:copy",
      "lucide:download",
      "lucide:upload",
      "lucide:share-2",
      "lucide:lock",
      "lucide:eye",
      "lucide:filter",
      "lucide:calendar",
      "lucide:clock",
      "lucide:info",
      "lucide:circle-alert",
      "lucide:log-out",
    ],
  },
  {
    id: "arrows",
    label: "Arrows",
    icons: [
      "lucide:arrow-right",
      "lucide:arrow-left",
      "lucide:arrow-up",
      "lucide:arrow-down",
      "lucide:arrow-up-right",
      "lucide:chevron-right",
      "lucide:chevron-down",
      "lucide:chevrons-up-down",
      "lucide:move",
      "lucide:refresh-cw",
      "lucide:rotate-ccw",
      "lucide:undo-2",
      "lucide:redo-2",
      "lucide:corner-down-right",
      "lucide:external-link",
      "lucide:maximize-2",
      "lucide:minimize-2",
      "lucide:shuffle",
      "lucide:repeat",
      "lucide:trending-up",
      "lucide:trending-down",
      "lucide:arrow-down-to-line",
      "lucide:arrow-up-from-line",
      "lucide:circle-arrow-right",
    ],
  },
  {
    id: "brands",
    label: "Brands",
    icons: [
      "simple-icons:github",
      "simple-icons:x",
      "simple-icons:linkedin",
      "simple-icons:instagram",
      "simple-icons:youtube",
      "simple-icons:discord",
      "simple-icons:figma",
      "simple-icons:slack",
      "simple-icons:notion",
      "simple-icons:vercel",
      "simple-icons:nextdotjs",
      "simple-icons:react",
      "simple-icons:vuedotjs",
      "simple-icons:svelte",
      "simple-icons:tailwindcss",
      "simple-icons:typescript",
      "simple-icons:producthunt",
      "simple-icons:dribbble",
      "simple-icons:behance",
      "simple-icons:reddit",
      "simple-icons:twitch",
      "simple-icons:spotify",
      "simple-icons:stripe",
      "simple-icons:openai",
    ],
  },
  {
    id: "developer",
    label: "Developer",
    icons: [
      "tabler:code",
      "tabler:terminal-2",
      "tabler:git-branch",
      "tabler:git-pull-request",
      "tabler:git-merge",
      "tabler:bug",
      "tabler:database",
      "tabler:server",
      "tabler:cloud",
      "tabler:api",
      "tabler:brackets",
      "tabler:braces",
      "tabler:package",
      "tabler:cpu",
      "tabler:device-desktop",
      "tabler:device-mobile",
      "tabler:webhook",
      "tabler:key",
      "tabler:shield-lock",
      "tabler:rocket",
      "tabler:bolt",
      "tabler:settings-automation",
      "tabler:file-code",
      "tabler:command",
    ],
  },
  {
    id: "design",
    label: "Design",
    icons: [
      "ph:paint-brush",
      "ph:palette",
      "ph:pen-nib",
      "ph:bezier-curve",
      "ph:selection",
      "ph:crop",
      "ph:magic-wand",
      "ph:eyedropper",
      "ph:text-aa",
      "ph:text-t",
      "ph:grid-four",
      "ph:layout",
      "ph:stack",
      "ph:shapes",
      "ph:circle-half",
      "ph:drop",
      "ph:frame-corners",
      "ph:ruler",
      "ph:image",
      "ph:sparkle",
      "ph:star-four",
      "ph:swatches",
      "ph:paint-bucket",
      "ph:cursor-click",
    ],
  },
  {
    id: "commerce",
    label: "Commerce",
    icons: [
      "lucide:shopping-cart",
      "lucide:shopping-bag",
      "lucide:store",
      "lucide:credit-card",
      "lucide:wallet",
      "lucide:receipt",
      "lucide:tag",
      "lucide:percent",
      "lucide:gift",
      "lucide:package",
      "lucide:truck",
      "lucide:banknote",
      "lucide:coins",
      "lucide:badge-dollar-sign",
      "lucide:chart-no-axes-column",
      "lucide:chart-pie",
      "lucide:chart-line",
      "lucide:target",
      "lucide:handshake",
      "lucide:briefcase",
      "lucide:building-2",
      "lucide:scale",
      "lucide:ticket",
      "lucide:qr-code",
    ],
  },
  {
    id: "communication",
    label: "Communication",
    icons: [
      "lucide:mail",
      "lucide:message-circle",
      "lucide:message-square",
      "lucide:send",
      "lucide:phone",
      "lucide:video",
      "lucide:mic",
      "lucide:at-sign",
      "lucide:inbox",
      "lucide:reply",
      "lucide:forward",
      "lucide:users",
      "lucide:user-plus",
      "lucide:contact",
      "lucide:megaphone",
      "lucide:rss",
      "lucide:bell-ring",
      "lucide:paperclip",
      "lucide:link",
      "lucide:smile",
      "lucide:thumbs-up",
      "lucide:heart",
      "lucide:bookmark",
      "lucide:flag",
    ],
  },
  {
    id: "media",
    label: "Media",
    icons: [
      "lucide:play",
      "lucide:pause",
      "lucide:circle-stop",
      "lucide:skip-forward",
      "lucide:skip-back",
      "lucide:volume-2",
      "lucide:volume-x",
      "lucide:music",
      "lucide:headphones",
      "lucide:camera",
      "lucide:film",
      "lucide:tv",
      "lucide:radio",
      "lucide:podcast",
      "lucide:image",
      "lucide:images",
      "lucide:clapperboard",
      "lucide:disc-3",
      "lucide:aperture",
      "lucide:scan",
      "lucide:cast",
      "lucide:gamepad-2",
      "lucide:book-open",
      "lucide:newspaper",
    ],
  },
  {
    id: "files",
    label: "Files",
    icons: [
      "lucide:file",
      "lucide:file-text",
      "lucide:file-image",
      "lucide:file-code",
      "lucide:file-spreadsheet",
      "lucide:file-archive",
      "lucide:folder",
      "lucide:folder-open",
      "lucide:folder-plus",
      "lucide:save",
      "lucide:hard-drive",
      "lucide:cloud-upload",
      "lucide:cloud-download",
      "lucide:clipboard",
      "lucide:clipboard-check",
      "lucide:notebook",
      "lucide:archive",
      "lucide:printer",
      "lucide:scissors",
      "lucide:layers",
      "lucide:list",
      "lucide:list-checks",
      "lucide:table",
      "lucide:kanban",
    ],
  },
  {
    id: "weather",
    label: "Weather and nature",
    icons: [
      "tabler:sun",
      "tabler:moon",
      "tabler:cloud",
      "tabler:cloud-rain",
      "tabler:cloud-storm",
      "tabler:snowflake",
      "tabler:wind",
      "tabler:temperature",
      "tabler:droplet",
      "tabler:rainbow",
      "tabler:sunrise",
      "tabler:sunset",
      "tabler:leaf",
      "tabler:tree",
      "tabler:flower",
      "tabler:mountain",
      "tabler:planet",
      "tabler:world",
      "tabler:map-pin",
      "tabler:compass",
      "tabler:flame",
      "tabler:bolt",
      "tabler:umbrella",
      "tabler:cloud-fog",
    ],
  },
];

/** Common searches offered as one-click suggestions. */
export const iconSearchSuggestions = [
  "arrow",
  "user",
  "cloud",
  "chart",
  "heart",
  "shield",
  "calendar",
  "github",
  "sparkle",
  "rocket",
];
