import type { contrastSection, focusSection } from "@/lib/a11y/contrast";
import type { Verdict } from "@/lib/a11y/readability";
import type { targetsSection } from "@/lib/a11y/targets";
import type { visionSection } from "@/lib/a11y/vision";
import type { A11yColors, A11yTypography, TouchTarget } from "@/types/a11y";

export type A11yReportInput = {
  colors: A11yColors;
  /** The focus ring being checked: the brand primary, or the lab's override. */
  focusRing: string;
  typography: A11yTypography;
  targets: TouchTarget[];
  targetGap: number;
};

export type A11yReportSections = {
  contrast: ReturnType<typeof contrastSection>;
  focusIndicator: ReturnType<typeof focusSection>;
  vision: ReturnType<typeof visionSection>;
  readability: {
    charactersPerLine: number;
    readingEase: number;
    gradeLevel: number;
    checks: { check: string; value: string; verdict: Verdict }[];
  };
  touchTargets: ReturnType<typeof targetsSection>;
};

export type A11yReport = {
  tool: "DesignHub Accessibility Lab";
  /** Stamped at download time so server and client renders stay identical. */
  generatedAt?: string;
  settings: A11yReportInput;
  sections: A11yReportSections;
};

/** Collects every check into one JSON document. Sections are contributed by each tool. */
export function buildReport(input: A11yReportInput, sections: A11yReportSections): A11yReport {
  return { tool: "DesignHub Accessibility Lab", settings: input, sections };
}

export function stampReport(report: A11yReport): string {
  return `${JSON.stringify({ ...report, generatedAt: new Date().toISOString() }, null, 2)}\n`;
}

export function stampMarkdown(report: A11yReport): string {
  return reportToMarkdown({ ...report, generatedAt: new Date().toISOString() });
}

const mark = (pass: boolean) => (pass ? "✅ Pass" : "❌ Fail");
const verdictMark: Record<Verdict, string> = { pass: "✅ Pass", warn: "⚠️ Warn", fail: "❌ Fail" };

/** Escapes what would break a GitHub table cell: pipes and line breaks. */
function cell(value: string | number): string {
  return String(value).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function table(head: string[], rows: (string | number)[][]): string {
  const line = (cells: (string | number)[]) => `| ${cells.map(cell).join(" | ")} |`;
  return [line(head), `| ${head.map(() => "---").join(" | ")} |`, ...rows.map(line)].join("\n");
}

const code = (value: string) => `\`${value.replace(/`/g, "")}\``;
const ratio = (value: number) => `${value.toFixed(2)}:1`;

/** One row per contrast pair, with the same rounded numbers as the JSON report. */
export function contrastTable(rows: A11yReportSections["contrast"]): string {
  return table(
    ["Check", "Colors", "Ratio", "Required", "Result", "AA", "AA large", "AAA", "AAA large", "APCA Lc", "APCA"],
    rows.map((row) => [
      row.check,
      `${code(row.foreground)} on ${code(row.background)}`,
      ratio(row.ratio),
      ratio(row.required),
      mark(row.pass) + (row.suggestion ? ` (try ${code(row.suggestion)})` : ""),
      mark(row.wcag.AA),
      mark(row.wcag["AA large"]),
      mark(row.wcag.AAA),
      mark(row.wcag["AAA large"]),
      `${row.apca.lc} (min ${row.apca.target})`,
      mark(row.apca.pass),
    ]),
  );
}

/** The ring against the page and against the focused button, each needing 3:1. */
export function focusTable(focus: A11yReportSections["focusIndicator"]): string {
  return table(
    ["Check", "Ring", "vs background", "vs component", "Required", "Result"],
    [
      [
        focus.check,
        code(focus.ring),
        `${ratio(focus.ratioAgainstBackground)} on ${code(focus.background)}`,
        `${ratio(focus.ratioAgainstComponent)} on ${code(focus.component)}`,
        ratio(focus.required),
        mark(focus.pass) + (focus.suggestion ? ` (try ${code(focus.suggestion)})` : ""),
      ],
    ],
  );
}

/** The same report as readable Markdown for pull requests and wikis. */
export function reportToMarkdown(report: A11yReport): string {
  const { settings, sections } = report;
  const { colors, typography } = settings;
  const visionPairs = sections.vision[0]?.pairs ?? [];
  const parts = [
    "# Accessibility report",
    `Generated by ${report.tool}${report.generatedAt ? ` on ${report.generatedAt}` : ""}.`,
    "## Settings",
    table(
      ["Setting", "Value"],
      [
        ["Text", code(colors.text)],
        ["Background", code(colors.background)],
        ["Accent", code(colors.accent)],
        ["On accent", code(colors.onAccent)],
        ["Focus ring", code(settings.focusRing)],
        ["Font", typography.family],
        ["Size", `${typography.size}px`],
        ["Weight", typography.weight],
        ["Line height", typography.lineHeight],
        ["Letter spacing", `${typography.letterSpacing}em`],
        ["Word spacing", `${typography.wordSpacing}em`],
        ["Measure", `${typography.measure}px`],
      ],
    ),
    "## Contrast",
    contrastTable(sections.contrast),
    sections.contrast[0] ? `> ${sections.contrast[0].apca.note}` : "",
    "## Focus indicator",
    focusTable(sections.focusIndicator),
    "## Color vision",
    "Contrast after simulating each type of color vision. AA needs 4.5:1.",
    table(
      ["Mode", ...visionPairs.map((item) => item.check)],
      sections.vision.map((mode) => [
        mode.mode,
        ...mode.pairs.map((item) => `${ratio(item.ratio)} ${item.passAA ? "✅" : "❌"}`),
      ]),
    ),
    "## Readability",
    `Characters per line: ${sections.readability.charactersPerLine}. Reading ease: ${sections.readability.readingEase}. Grade level: ${sections.readability.gradeLevel}.`,
    table(
      ["Check", "Value", "Result"],
      sections.readability.checks.map((item) => [item.check, item.value, verdictMark[item.verdict]]),
    ),
    "## Touch targets",
    `Gap between targets: ${sections.touchTargets.gap}px.`,
    table(
      ["Target", "Size", "WCAG 2.5.8 (AA)", "WCAG 2.5.5 (AAA)", "Note"],
      sections.touchTargets.results.map((item) => [
        item.label,
        item.size,
        mark(item["WCAG 2.5.8 (AA)"]),
        mark(item["WCAG 2.5.5 (AAA)"]),
        item.note,
      ]),
    ),
  ];
  return `${parts.filter(Boolean).join("\n\n")}\n`;
}
