import { effectStylesheet, hexToRgba, px } from "@/lib/effects/css";
import { defaultEffectContext } from "@/lib/effects/define";
import { effectDefinitions, generateEffect } from "@/lib/effects/registry";
import { shadowValue } from "@/lib/effects/shadow";
import type { EffectContext, EffectKind, EffectSettingsMap } from "@/types/effects";

/** Every effect as one stylesheet with `.fx-*` classes. */
export function effectsBundle(settings: EffectSettingsMap, context: EffectContext = defaultEffectContext): string {
  const blocks = effectDefinitions.map((definition) => {
    const kind: EffectKind = definition.kind;
    const effect = generateEffect(kind, settings[kind], context);
    return effect ? `/* ${definition.label} */\n${effectStylesheet(effect, `.fx-${kind}`)}` : "";
  });
  return `/* Effects generated by DesignHub */\n\n${blocks.filter(Boolean).join("\n")}`;
}

export type EffectToken = { name: string; value: string };

/** Effects as design tokens. Names follow Tailwind v4's --shadow-* and --blur-* namespaces. */
export function effectTokens(settings: EffectSettingsMap): EffectToken[] {
  const glow = settings.glow;
  return [
    { name: "shadow-card", value: shadowValue(settings.shadow.layers) },
    { name: "shadow-glow", value: `0 0 ${px(glow.radius * 0.55)} ${hexToRgba(glow.color, glow.intensity * 0.6)}` },
    { name: "blur-glass", value: px(settings.glass.blur) },
  ];
}
